### ISSUE TITLE
Where can I search these aliyun images?

### ISSUE THREAD

**Issue by fengredrum** [shikanon/kubeflow-manifests#46]
Could you kindly tell me where can I search aliyun images, like `registry.cn-shenzhen.aliyuncs.com/tensorbytes/notebook-servers-jupyter-tensorflow-full:v1.3.0-rc.0-59b7b`?

Just like we can search docker images and their corresponding tags in DockerHub as showing in the down below fig
![Screen Shot 2021-07-16 at 15 45 33](https://user-images.githubusercontent.com/26370917/125915025-cd64ca8d-c15c-45bd-88bf-9af8f06c5912.png)

**Comment by shikanon** [comment]
@fengredrum you can search the aliyun mirro when you login in the [aliyun cloud](https://www.aliyun.com/product/acr?spm=5176.19720258.J_8058803260.371.54212c4aMPAyWl). I create this repo because of the origin image is outside on the firewall, if you not have this problem, you can use kubeflow office images.

**Comment by fengredrum** [comment]
I login the aliyun's console, but I still can't find this image: 
`registry.cn-shenzhen.aliyuncs.com/tensorbytes/notebook-servers-jupyter-tensorflow-full:v1.3.0-rc.0-59b7b` 😣

![image](https://user-images.githubusercontent.com/26370917/126103528-cd8d08ac-7adb-48d6-a411-a6e03adb197f.png)

**Comment by shikanon** [comment]
@fengredrum you can pull the image not need login, the images is I pull the origin image and push the aliyunclouds

**Comment by fengredrum** [comment]
Thx
